import json

def get_nested(data, keys):
    try:
        for key in keys:
            data = data[key]
        return data
    except (KeyError, TypeError):
        return None

data = json.load(open('message.json'))
print(len(data))
schema = {}
schema["rawHomeStatusCd"] = data[0].get("rawHomeStatusCd")
schema["marketingStatusSimplifiedCd"] = data[0].get("marketingStatusSimplifiedCd")
schema["imgSrc"] = data[0].get("imgSrc")
schema["hasImage"] = data[0].get("hasImage")
schema["detailUrl"] = data[0].get("detailUrl")
schema["statusType"] = data[0].get("statusType")
schema["statusText"] = data[0].get("statusText")
schema["countryCurrency"] = data[0].get("countryCurrency")
schema["price"] = data[0].get("price")
schema["unformattedPrice"] = data[0].get("unformattedPrice")
schema["address"] = data[0].get("address")
schema["addressStreet"] = data[0].get("addressStreet")
schema["addressCity"] = data[0].get("addressCity")
schema["addressState"] = data[0].get("addressState")
schema["addressZipcode"] = data[0].get("addressZipcode")
schema["isUndisclosedAddress"] = data[0].get("isUndisclosedAddress")
schema["shouldShowRequestOnPrice"] = data[0].get("shouldShowRequestOnPrice")
schema["beds"] = data[0].get("beds")
schema["baths"] = data[0].get("baths")
schema["area"] = data[0].get("area")
schema["isZillowOwned"] = data[0].get("isZillowOwned")
schema["flexFieldText"] = data[0].get("flexFieldText")
schema["contentType"] = data[0].get("contentType")
schema["latitude"] = get_nested(data[0], ["latLong", "latitude"])
schema["longitude"] = get_nested(data[0], ["latLong", "longitude"])
schema["streetAddress"] = get_nested(data[0], ["hdpData", "homeInfo", "streetAddress"])
schema["zipcode"] = get_nested(data[0], ["hdpData", "homeInfo", "zipcode"])
schema["city"] = get_nested(data[0], ["hdpData", "homeInfo", "city"])
schema["state"] = get_nested(data[0], ["hdpData", "homeInfo", "state"])
schema["latitude"] = get_nested(data[0], ["hdpData", "homeInfo", "latitude"])
schema["longitude"] = get_nested(data[0], ["hdpData", "homeInfo", "longitude"])
schema["price"] = get_nested(data[0], ["hdpData", "homeInfo", "price"])
schema["bathrooms"] = get_nested(data[0], ["hdpData", "homeInfo", "bathrooms"])
schema["bedrooms"] = get_nested(data[0], ["hdpData", "homeInfo", "bedrooms"])
schema["livingArea"] = get_nested(data[0], ["hdpData", "homeInfo", "livingArea"])
schema["homeType"] = get_nested(data[0], ["hdpData", "homeInfo", "homeType"])
schema["homeStatus"] = get_nested(data[0], ["hdpData", "homeInfo", "homeStatus"])
schema["daysOnZillow"] = get_nested(data[0], ["hdpData", "homeInfo", "daysOnZillow"])
schema["isFeatured"] = get_nested(data[0], ["hdpData", "homeInfo", "isFeatured"])
schema["shouldHighlight"] = get_nested(data[0], ["hdpData", "homeInfo", "shouldHighlight"])
schema["zestimate"] = get_nested(data[0], ["hdpData", "homeInfo", "zestimate"])
schema["rentZestimate"] = get_nested(data[0], ["hdpData", "homeInfo", "rentZestimate"])
schema["is_FSBA"] = get_nested(data[0], ["hdpData", "homeInfo", "listing_sub_type", "is_FSBA"])
schema["is_openHouse"] = get_nested(data[0], ["hdpData", "homeInfo", "listing_sub_type", "is_openHouse"])
schema["openHouse"] = get_nested(data[0], ["hdpData", "homeInfo", "openHouse"])
schema["isUnmappable"] = get_nested(data[0], ["hdpData", "homeInfo", "isUnmappable"])
schema["isPreforeclosureAuction"] = get_nested(data[0], ["hdpData", "homeInfo", "isPreforeclosureAuction"])
schema["homeStatusForHDP"] = get_nested(data[0], ["hdpData", "homeInfo", "homeStatusForHDP"])
schema["priceForHDP"] = get_nested(data[0], ["hdpData", "homeInfo", "priceForHDP"])
schema["timeOnZillow"] = get_nested(data[0], ["hdpData", "homeInfo", "timeOnZillow"])
schema["isNonOwnerOccupied"] = get_nested(data[0], ["hdpData", "homeInfo", "isNonOwnerOccupied"])
schema["isPremierBuilder"] = get_nested(data[0], ["hdpData", "homeInfo", "isPremierBuilder"])
schema["isZillowOwned"] = get_nested(data[0], ["hdpData", "homeInfo", "isZillowOwned"])
schema["currency"] = get_nested(data[0], ["hdpData", "homeInfo", "currency"])
schema["country"] = get_nested(data[0], ["hdpData", "homeInfo", "country"])
schema["taxAssessedValue"] = get_nested(data[0], ["hdpData", "homeInfo", "taxAssessedValue"])
schema["lotAreaValue"] = get_nested(data[0], ["hdpData", "homeInfo", "lotAreaValue"])
schema["lotAreaUnit"] = get_nested(data[0], ["hdpData", "homeInfo", "lotAreaUnit"])
schema["isShowcaseListing"] = get_nested(data[0], ["hdpData", "homeInfo", "isShowcaseListing"])
schema["isSaved"] = data[0].get("isSaved")
schema["isUserClaimingOwner"] = data[0].get("isUserClaimingOwner")
schema["isUserConfirmedClaim"] = data[0].get("isUserConfirmedClaim")
schema["pgapt"] = data[0].get("pgapt")
schema["sgapt"] = data[0].get("sgapt")
schema["zestimate_top"] = data[0].get("zestimate")
schema["shouldShowZestimateAsPrice"] = data[0].get("shouldShowZestimateAsPrice")
schema["has3DModel"] = data[0].get("has3DModel")
schema["hasVideo"] = data[0].get("hasVideo")
schema["isHomeRec"] = data[0].get("isHomeRec")
schema["hasAdditionalAttributions"] = data[0].get("hasAdditionalAttributions")
schema["isFeaturedListing"] = data[0].get("isFeaturedListing")
schema["isShowcaseListing_top"] = data[0].get("isShowcaseListing")
schema["list"] = data[0].get("list")
schema["relaxed"] = data[0].get("relaxed")
schema["info6String"] = data[0].get("info6String")
schema["brokerName"] = data[0].get("brokerName")
schema["hasOpenHouse"] = data[0].get("hasOpenHouse")
schema["openHouseStartDate"] = data[0].get("openHouseStartDate")
schema["openHouseEndDate"] = data[0].get("openHouseEndDate")
schema["openHouseDescription"] = data[0].get("openHouseDescription")
schema["isPaidBuilderNewConstruction"] = data[0].get("isPaidBuilderNewConstruction")



print(schema)